# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'telemedicineApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for telemedicineApp

  target 'telemedicineAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'telemedicineAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'SCLAlertView'

end
